# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(678, 547)
        MainWindow.setMinimumSize(QtCore.QSize(390, 220))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 654, 229))
        self.page.setObjectName("page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_datafolder = QtWidgets.QLineEdit(self.page)
        self.lineEdit_datafolder.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_datafolder.setReadOnly(True)
        self.lineEdit_datafolder.setObjectName("lineEdit_datafolder")
        self.gridLayout_7.addWidget(self.lineEdit_datafolder, 0, 0, 1, 2)
        self.btn_tool_choose_fem_folder = QtWidgets.QToolButton(self.page)
        self.btn_tool_choose_fem_folder.setObjectName("btn_tool_choose_fem_folder")
        self.gridLayout_7.addWidget(self.btn_tool_choose_fem_folder, 0, 2, 1, 1)
        self.btn_extract_fem = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_extract_fem.sizePolicy().hasHeightForWidth())
        self.btn_extract_fem.setSizePolicy(sizePolicy)
        self.btn_extract_fem.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_extract_fem.setObjectName("btn_extract_fem")
        self.gridLayout_7.addWidget(self.btn_extract_fem, 3, 0, 1, 2)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 654, 194))
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_tool_choose_data_file = QtWidgets.QToolButton(self.page_2)
        self.btn_tool_choose_data_file.setObjectName("btn_tool_choose_data_file")
        self.gridLayout_2.addWidget(self.btn_tool_choose_data_file, 2, 3, 1, 1)
        self.btn_tool_choose_mapping_file = QtWidgets.QToolButton(self.page_2)
        self.btn_tool_choose_mapping_file.setObjectName("btn_tool_choose_mapping_file")
        self.gridLayout_2.addWidget(self.btn_tool_choose_mapping_file, 2, 1, 1, 1)
        self.lineEdit_mapping_file = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mapping_file.sizePolicy().hasHeightForWidth())
        self.lineEdit_mapping_file.setSizePolicy(sizePolicy)
        self.lineEdit_mapping_file.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mapping_file.setReadOnly(True)
        self.lineEdit_mapping_file.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_mapping_file.setClearButtonEnabled(True)
        self.lineEdit_mapping_file.setObjectName("lineEdit_mapping_file")
        self.gridLayout_2.addWidget(self.lineEdit_mapping_file, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 2, 1, 1)
        self.btn_get_mapping_file = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_get_mapping_file.sizePolicy().hasHeightForWidth())
        self.btn_get_mapping_file.setSizePolicy(sizePolicy)
        self.btn_get_mapping_file.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_get_mapping_file.setObjectName("btn_get_mapping_file")
        self.gridLayout_2.addWidget(self.btn_get_mapping_file, 3, 0, 1, 1)
        self.lineEdit_data_file = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_file.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_file.setSizePolicy(sizePolicy)
        self.lineEdit_data_file.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_data_file.setReadOnly(True)
        self.lineEdit_data_file.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_data_file.setClearButtonEnabled(True)
        self.lineEdit_data_file.setObjectName("lineEdit_data_file")
        self.gridLayout_2.addWidget(self.lineEdit_data_file, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 2, 1, 1)
        self.lineEdit_mapping_file_res = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mapping_file_res.sizePolicy().hasHeightForWidth())
        self.lineEdit_mapping_file_res.setSizePolicy(sizePolicy)
        self.lineEdit_mapping_file_res.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_mapping_file_res.setReadOnly(True)
        self.lineEdit_mapping_file_res.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_mapping_file_res.setClearButtonEnabled(True)
        self.lineEdit_mapping_file_res.setObjectName("lineEdit_mapping_file_res")
        self.gridLayout_2.addWidget(self.lineEdit_mapping_file_res, 5, 2, 1, 1)
        self.btn_tool_choose_mapping_file_res = QtWidgets.QToolButton(self.page_2)
        self.btn_tool_choose_mapping_file_res.setObjectName("btn_tool_choose_mapping_file_res")
        self.gridLayout_2.addWidget(self.btn_tool_choose_mapping_file_res, 5, 3, 1, 1)
        self.btn_applymap = QtWidgets.QPushButton(self.page_2)
        self.btn_applymap.setObjectName("btn_applymap")
        self.gridLayout_2.addWidget(self.btn_applymap, 6, 2, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 654, 151))
        self.page_5.setObjectName("page_5")
        self.toolBox.addItem(self.page_5, "")
        self.gridLayout.addWidget(self.toolBox, 2, 0, 1, 1)
        self.btn_save_table = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_table.setObjectName("btn_save_table")
        self.gridLayout.addWidget(self.btn_save_table, 5, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 0))
        self.statusBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Портфель ИТ и ЦТ"))
        self.lineEdit_datafolder.setPlaceholderText(_translate("MainWindow", "choose folder"))
        self.btn_tool_choose_fem_folder.setText(_translate("MainWindow", "..."))
        self.btn_extract_fem.setText(_translate("MainWindow", "Extract FEM"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "1. Extraction FEM files"))
        self.btn_tool_choose_data_file.setText(_translate("MainWindow", "..."))
        self.btn_tool_choose_mapping_file.setText(_translate("MainWindow", "..."))
        self.lineEdit_mapping_file.setPlaceholderText(_translate("MainWindow", "choose file"))
        self.label_9.setText(_translate("MainWindow", "Mapping file"))
        self.label_14.setText(_translate("MainWindow", "Extraction file"))
        self.btn_get_mapping_file.setText(_translate("MainWindow", "Get mapping file"))
        self.lineEdit_data_file.setPlaceholderText(_translate("MainWindow", "choose file"))
        self.label_10.setText(_translate("MainWindow", "Result mapping file"))
        self.lineEdit_mapping_file_res.setPlaceholderText(_translate("MainWindow", "choose file"))
        self.btn_tool_choose_mapping_file_res.setText(_translate("MainWindow", "..."))
        self.btn_applymap.setText(_translate("MainWindow", "Apply mapping"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "2. Mapping"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "3. Calculation"))
        self.btn_save_table.setText(_translate("MainWindow", "Export to Excel"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

